### PR TITLE
Duplicate Line or Block, New Line Before/After Current

### PR DESCRIPTION
**Pull request by StJohn3D**
What is the correct way to build/export for this project?

Added SublimeText keymaps for the following

cmd+shft+D
- Duplicate Line or Block

cmd+shft+enter
- New line before Current

cmd+enter
- New line after current

What I did was file export settings and just exported my keymaps.

### CODE REVIEW

**Comment by EHLOVader** [comment]
Great contribution! I remember having to add that myself. 

I may be speaking out of turn but ever since I contributed the xml and build system the binaries probably shouldn't be updated directly.

There are no sensible diffs when the binary files are the ones changing. 

I should probably submit a PR for Shawn McCool with a proper CONTRIBUTING.md but until I do, could you make this a PR which modifies the src xml instead? 

The [OSX keymaps are here](https://github.com/ShawnMcCool/PHPStorm-SpacePeacock/blob/master/osx-key-mappings/keymaps/Mac%20OS%20X%2010_5_%20Sublime.xml) and the [windows/linux keymaps are here](https://github.com/ShawnMcCool/PHPStorm-SpacePeacock/tree/master/win_linux-keymaps-only/keymaps)

**Comment by StJohn3D** [comment]
Thank you, yes I saw that there was now XML for tracking diffs but searching the wiki and elsewhere I couldn't find any documentation on how to use them. So I exported a jar file just to have something to commit so I could make a pull request and ask how to contribute properly above.

Band new to jetBrains IDEs. When I get more time I'll try to figure out where/how to edit XML files and test them in my IDE. A CONTRIBUTING.md would be _extremely_ helpful.

**Comment by EHLOVader** [comment]
Added a CONTRIBUTING file and sent in a pull request. 

I need to add more on how to reverse the build, I bet that would help you, and might run through it myself to audit the process to make sure I didn't miss anything, to add your PR. 

https://github.com/ShawnMcCool/PHPStorm-SpacePeacock/pull/18

**Comment by ShawnMcCool** [comment]
I'm slow. If I'm every _TOO_ slow, you can ping me on twitter etc. Sorry!

**Pull request merged**
