### PR TITLE
Update with past master changes prior to extracting Jars

### PR DESCRIPTION
**Pull request by EHLOVader**
I have extracted the jars here for improved version control.

This should make the changes clear and can even clean up some of the unwanted extra bits that were tied into the exports.

### CODE REVIEW

**Comment by EHLOVader** [comment]
I have added release downloads to my fork as an example of how the build process could be externalized offering just the configuration in the repo. https://github.com/EHLOVader/PHPStorm-SpacePeacock/releases/tag/1.8

**Comment by ShawnMcCool** [comment]
Umm.. wow, this pull request is ancient.. 

Sorry?

Is there any way you could update this branch with new stuff so I can merge it in.

Again, sorry.

**Comment by EHLOVader** [comment]
Might have a chance to look at it. Kind of gave up on it and looked into starting a keymap only project of my own. 

Would love to help if I can though.

Can look into rebasing it this week, even though I am not sure what that would look like since this was converting the binaries to their components.

**Comment by EHLOVader** [comment]
Updated to the latest keymaps.

I also fixed the build script but it may need some adjustments.
It doesn't add the project name to the filename like the binaries are now.
And it needs more information about how to use it in the readme.

**Comment by ShawnMcCool** [comment]
@EHLOVader what's the correct build procedure?  ./build.sh . ?

**Comment by EHLOVader** [comment]
Sorry, I thought it was put somewhere, but it must have been missed. You must pass the directory name for the package you wish to build. 

```
./build.sh osx-key-mappings
./build.sh styles-only
./build.sh win_linux-keymaps-only
```

That should produce an importable jar.

**Comment by ShawnMcCool** [comment]
I want to merge this in. I just need to find the time to update the docs and test and make everything work. I'll try to get this in this week... *crosses fingers*

**Comment by EHLOVader** [comment]
Updated the title on this. #10 didn't include the rebase of this in it, so the changes to `master` which happened between the two weren't included in #10 but were added here in 8f19214... I did a quick update rebasing this with the new master after #10 was merged, and updated the build script some and moved builds into a folder which should help streamline things some.

**Comment by ShawnMcCool** [comment]
Thanks =)

**Pull request merged**
